services:
  api01:
    image: api-sample-share-redis
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      - Redis__ConnectionString=redis
  
  api02:
    image: api-sample-share-redis
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      - Redis__ConnectionString=redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    